version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes: # Optional for development
      - ./src:/app/src
    stdin_open: true
    tty: true
    container_name: react-app
    restart: unless-stopped
